apiVersion: apps/v1
kind: Deployment
metadata:
        name: capstoneprintoutput
spec:
  replicas: 2
  selector:
          matchLabels:
                  app: capstoneprintoutput
  template:
    metadata:
      labels:
        app: capstoneprintoutput
    spec:
      containers:
      - image: aronanubhav/capstoneprintoutput
        name: capstoneprintoutput
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 30000000
